### ISSUE TITLE
Rocket Chat SSL error, blank page (using with Trust invalid authority certificate)

### ISSUE THREAD

**Issue by LXSysadmin** [ramboxapp/community-edition#612]
### Steps to reproduce

1. Install Rambox
2. Add Rocket chat server as Rocket Chat service or _Custom Service with custom SSL like https://rocket.lan
3. Get blank page

### Expected behavior

In previous version RocketChat was working like _Custom Service with Trust invalid authority certificate

### Actual behavior

Now in version 0.5.2 Rocket Chat stop working at all. This is local Rocket Chat server with custom SSL. Like https://rocket.lan, so, RamBox does not support anymore untrusted SSL?

### ENVIRONMENT

> Rambox: v0.5.2

> OS: Windows 10

> Arch: x64 

> Rocket Chat server version: 0.49.4

**Comment by peterwilli** [comment]
I got this too with other services (non custom services) like skype and wire and whatsapp. I had to move back to chrome sticky tabs because of this :(

**Comment by LXSysadmin** [comment]
Whatsup and FB messenger are working fine for me.

**Comment by peterwilli** [comment]
Yeah I saw they updated it, should work now.

**Comment by saenzramiro** [comment]
Is this still happening?

**Comment by drasill** [comment]
I've got the same problem with Zimbra (self signed certificate).

It doesn't work when using the "zimbra" service, neither with the "_custom" service with trush checked.

**Comment by saenzramiro** [comment]
To fix this bug, I will need a URL of any website with invalid SSL. Can anyone share to me this info?

**Comment by hombrepac** [comment]
Still happening. Let me see if I can provide you a custom cert to test.

**Comment by zlo2107** [comment]
I think this is electron issue and there is not much can be done. You can test this issue by links provided by badssl.com , for example:

[https://self-signed.badssl.com](https://self-signed.badssl.com/)

Add custom service and page will be blank.

There is workaround I found for this types of issues, if you add to electron/main.js:

> app.commandLine.appendSwitch('ignore-certificate-errors');

That "solve" the problem. Maybe there is solution to add in settings something like "Ignore certificate errors" with warning that this option is for advanced user and you giving up security and etc.

**Comment by luandrea** [comment]
@Matt-Soft  How can I try your work-around in Rambox-0.5.14? I have only one big file called rambox...

**Comment by Matt-Soft** [comment]
@luandrea what operating system do you use?

**Comment by luandrea** [comment]
Hi Matt-Soft, I'm using Ubuntu 17.10.

**Comment by Matt-Soft** [comment]
@luandrea So the easiest way is to follow instructions from:
[https://github.com/saenzramiro/rambox#compile-on-ubuntu](url)
After step 4 you have to edit file "main.js" located in directory "electron" and add at the end:
> app.commandLine.appendSwitch('ignore-certificate-errors');

**Comment by ssaip** [comment]
Under linux, you could also add the custom certificate to nssdb and restart Rambox.

**Comment by luzankia** [comment]
I still have this issue with Rambox 0.5.17 on Win 10 x64.
The Webmin of my NAS did workt some time ago but it's like a year that I'm stuck with a white page.
I use a self signed certificate and did check the "Trust invalid authority certificates" without luck.
