### ISSUE TITLE
Microsoft Team with Active Directory

### ISSUE THREAD

**Issue by cecton** [ramboxapp/community-edition#997]
If your company is using credentials from Active Directory, as soon as you entered the email, you get redirected to a blank page. On a regular browser you get a login popup where you need to insert your username and password.

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> linux x64 4.11.9-1-ARCH

**Comment by cduranleau** [comment]
+1

**Comment by cduranleau** [comment]
So this has been bugging me as well but I don't know much about Rambox. I hope it's as simple as adding something like  
```
,allow_popups: true
```

that gmail already uses. I'm going TRY to get it working on it locally but no promises.  

1. https://github.com/Thalagyrt/rambox/blob/bc8517703a3e22c8e41423ab1099ee44b8813046/app/store/ServicesList.js#L118

**Comment by cecton** [comment]
Thx! I will do the test too just in case the problem is more complex than what it looks...

**Comment by cecton** [comment]
I just tested on master with the change and it works. Then I re-cloned, compiled again and tested again and it works too. So maybe the problem has been fixed in the mean time. (Or maybe my environment was not perfectly clean...)

Let me know if it works for you tooe

**Comment by cduranleau** [comment]
So I've never actually cloned the project before, so I'm struggling to get it to start from master. I'm following the instructions here [1], and I installed npm, sencha, and electron with brew but I'm running into an error on 

```
npm run sencha:compile

> @ sencha:compile /Users/my_id/Work/git/rambox
> sencha app build && cp app/package.json build/production/Rambox/ && npm --prefix ./build/production/Rambox/ install ./build/production/Rambox/

Sencha Cmd v6.5.0.180
[INF] Using GPL version of Ext JS version 5.1.1.451 from /Users/my_id/Work/git/rambox/ext.
[INF] The implications of using GPL version can be found here (http://www.sencha.com/products/extjs/licensing).
[INF] Processing Build Descriptor : default (production environment)
[INF] Loading compiler context
[INF] Loading app json manifest...
[INF] Appending content to /Users/my_id/Work/git/rambox/bootstrap.js
[INF] Writing content to /Users/my_id/Work/git/rambox/bootstrap.json
[INF] Processing data with CmdJavascriptCompressor
[INF] Writing concatenated output to file /Users/my_id/Work/git/rambox/build/production/Rambox/app.js
[INF] merging 418 input resources into /Users/my_id/Work/git/rambox/build/production/Rambox/resources
[INF] merged 0 resources into /Users/my_id/Work/git/rambox/build/production/Rambox/resources
[INF] merging 5 input resources into /Users/my_id/Work/git/rambox/build/production/Rambox
[INF] merged 0 resources into /Users/my_id/Work/git/rambox/build/production/Rambox
[INF] Writing content to /Users/my_id/Work/git/rambox/sass/example/bootstrap.json
[INF] Writing content to /Users/my_id/Work/git/rambox/sass/example/bootstrap.js
[INF] writing sass content to /Users/my_id/Work/git/rambox/build/temp/production/Rambox/sass/Rambox-all.scss.tmp
[INF] appending sass content to /Users/my_id/Work/git/rambox/build/temp/production/Rambox/sass/Rambox-all.scss.tmp
[INF] appending sass content to /Users/my_id/Work/git/rambox/build/temp/production/Rambox/sass/Rambox-all.scss.tmp
[ERR] The following error occurred while executing this line:
/Users/my_id/Work/git/rambox/.sencha/app/build-impl.xml:285: The following error occurred while executing this line:
/Users/my_id/Work/git/rambox/.sencha/app/sass-impl.xml:189: The following error occurred while executing this line:
/Users/my_id/Work/git/rambox/.sencha/app/sass-impl.xml:235: Problem: failed to create task or type x-compass-compile
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

[ERR] 
[ERR] The application was last modified by an older version of Sencha Cmd (6.1.2.15).
[ERR] Running "sencha app upgrade" may resolve the error described above.
[ERR] 
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! @ sencha:compile: `sencha app build && cp app/package.json build/production/Rambox/ && npm --prefix ./build/production/Rambox/ install ./build/production/Rambox/`
npm ERR! Exit status 65
npm ERR! 
npm ERR! Failed at the @ sencha:compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/my_id/.npm/_logs/2017-08-23T16_06_09_293Z-debug.log
```

But if you have it working(and it's been fixed in master) I'll trust your testing.


1. https://github.com/saenzramiro/rambox#getting-started

**Comment by nmat** [comment]
@cduranleau which system are you compiling on? and did you install the extra thing during sencha:

Sencha Cmd 6.1.2.15 (**make sure to check "Compass extension" during install if you don't have installed yet**)

**Comment by cduranleau** [comment]
Ahhh I bet that's it. Since I installed from brew I didn't see that option. I'll dig in ASAP.

**Comment by nmat** [comment]
FYI I have not tested compiling under "ubuntu on windows" since there could be problems on the running of applications that is not really windows specific. (this is also something that is noted from the blogs on ubuntu on windows since there is no real X server running)

However you might be able to run it with a X server on the side but I think it is hard to get it working correctly.

**Comment by cecton** [comment]
I just tested this morning at work with master and it wasn't working. I talked to a colleague in IT who told me that the mechanism to log in is different when you are inside the network and outside.

So I tested now with the version 0.5.9 and I can login properly.

So the problem is still there but to reproduce it I need to be inside my company's network...

**Comment by cduranleau** [comment]
@nmat++ Thank you. Reinstalling with the "Compass extension" option got a development instance up and running. After that I tried out the all_popups change but it didn't work.
```
,allow_popups: true
```
@cecton I'll try out the 'on network' vs. 'off network' idea tonight.

**Comment by nmat** [comment]
@cduranleau perfect please inform what you can find out of the issue you are encountering. Always good to have more feedback

**Comment by cduranleau** [comment]
Sorry I had been out of town for a wedding. I am able to login to Teams using Rambox when not on our work network. I'll dig into the developer tools to see exactly what errors are happening(on the different networks) over lunch.

**Comment by cduranleau** [comment]
So when logging in from Rambox, the service is returning a 401 unauthorized and then blocks. When copying the request into chrome, the browser pops up a basic-authentication prompt allowing me to continue the login process. 

After finding that 'basic-auth' prompt in chrome, I searched the Rambox issues and found this[1]. :/ Might not be able to use ANY service that pops a 'basic-auth' prompt.

1. https://github.com/saenzramiro/rambox/issues/378

**Comment by cduranleau** [comment]
With some guessing, I was able to log into teams. I had to add the following info but this actually got me through the login into teams. I have no idea how to prompt an auth box and put the username/password into that callback though...

```$ git diff
diff --git a/electron/main.js b/electron/main.js
index 4c56434..ab8cf35 100644
--- a/electron/main.js
+++ b/electron/main.js
@@ -466,3 +466,8 @@ app.on('activate', function () {
 app.on('before-quit', function () {
        isQuitting = true;
 });
+
+app.on('login', function (event, webContents, request, authInfo, callback) {
+       event.preventDefault();
+       callback('username', 'password');
+});
```
